const cheeses = [
  {
    src: "/Noord-Hollander-Gouda-pd-1.avif",
    name: "Noord Hollander Gouda",
    ingredients: [
      "Umami",
      "Caramel Corn",
      "Crystalline Crunch",
      "Cow Milk",
      "Pasteurized",
      "Age: 3-4 Years",
    ],
    price: 25,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Old-Farmdal-pd-1.avif",
    name: "Old Farmdal",
    ingredients: [
      "Ripe Cherry",
      "Dark Chocolate",
      "Crystalline Crunch",
      "Cow Milk",
      "Pasteurized",
      "Age: 10-12 Months",
    ],
    price: 36,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Lowry-Hill-Provisions-Red-Locks-Salami-pd-1.avif",
    name: "Lowry Hill Provisions Red Locks Salami",
    ingredients: ["Whiskey", "Nutmeg", "Rich"],
    price: 21,
    unit: "oz each",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Murray's-Cave-Aged-Reserve-Hudson-Flower-pd-1.avif",
    name: "Murray's Cave Aged Reserve Hudson Flower",
    ingredients: [
      "Rich",
      "Creamy",
      "Piney",
      "Sheep Milk",
      "Pasteurized",
      "Age: 4-8 Weeks",
    ],
    price: 35,
    unit: "oz wheel",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Murray's-Cave-Aged-Original-Stockinghall-Cheddar-pd-1.avif",
    name: "Murray's Cave Aged Original Stockinghall Cheddar",
    ingredients: [
      "Meaty",
      "Sour Cream",
      "Pineapple",
      "Cow Milk",
      "Pasteurized",
      "Age: 10-12 Months",
    ],
    price: 30,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Couronne-de-Reines-pd-1.avif",
    title: "Murray's Cave Aged Limited Couronne de Reines",
    name: "Couronne-de-Reines",
    price: 21,
    unit: "6 oz wheel",
    desc: "With its ring shape and ashed grey rind, Couronne de Reines looks more like a donut from outer space than a Loire Valley chèvre. But that’s where it originates before it arrives at our cheese caves in Queens (“Reines” in French). Like Selles-sur-Cher but a bit firmer, it has a thin, wrinkled rind cloaking a perfectly tangy clay-like middle with notes of sea salt and fresh grass. On a board with Jambon de Bayonne, this distinctive goat is equal parts conversation-starting and mouth-watering.",
    review:
      "“Having this donut shape on my cheese board is such a fun, whimsical touch. I like to balance the salty tang with V Smiley Strawberry Italian Plum Rosewater Jam and a glass of Sancerre.”",
    ingredients: [
      "Pasteurized Goat's Milk",
      "Animal Rennet",
      "Lactic Starters",
      "Salt",
      "Food Coloring: Black Carbon",
      "Age: 3-5 weeks",
    ],
    allergens: ["milk"],
    details: [
      "Couronne de Reines is a limited-edition addition to our line-up of Loire Valley chèvres, which are a cornerstone of our caves program.",
      "As is the case for all of our Loires, we get unaged cheese directly from Rodolphe le Meunier, a renowned French cheesemaker.",
      "The corresponding ring-shaped Rodolphe cheese is called Couronne de Fontenay (“couronne” meaning crown), so we called ours Couronne de Reines (Queens, where our cheese caves are located).",
      "Our caves team coats the cheese is vegetable ash, a traditional affinage practice that dates back centuries.",
      "The vegetable ash lowers the cheese's acidity level, which means the mold rind can grow more quickly and absorb moisture as the cheese dries out. ",
      "We nurture the rind in a warm, humid environment before drying the cheese to allow the rind to grow rapidly. It then spends a few days in our Bloomy Rind Cave before it's released at three weeks old.",
      "The brainy, wrinkled rind is known as a geo rind, formed by the yeast Geotrichum candidum.",
    ],
    makerInfo: [
      "At Murray's, we are cheese experts and enthusiasts who make, source, sell, and serve exceptional cheese and specialty foods nationwide.",
      "The Murray's Cheese branded product line comprises deliciously distinct, time-honored products made with the finest ingredients by passionate producers across the globe.",
      "These products have been hand-selected by our trusted cheesemongers, who travel the world to taste countless items in search of flavors that are exceptional enough to be included in our branded product line.",
      "We build strong relationships with our talented production partners. They trust our team to handle the extraordinary goods they've worked hard to perfect, as we bring them to households across the country.",
      "Whether you're looking for Gruyère from Switzerland, Brie from France, or Prosciutto di Parma from Italy, with a Murray's branded product, you'll receive our favorite version of a traditional product at an incredible value.",
    ],
    makerFacts: ["Family Owned"],
    storageTips:
      "When you receive your cheese, unpack the order and refrigerate the items. We recommend using the cheese paper we send most of our products in to store the cheese. The cheese paper helps cover the items and stop them from drying out, while also allowing the cheese to breathe. Since cheese is mold, it's a living thing! If you cut off air circulation to the cheese, you can actually cause it to suffocate and spoil at a faster rate.",
    images: ["/Couronne-de-Reines-pd-1.avif", "/Couronne-de-Reines-pd-2.avif"],
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Goat-Lady-Dairy-Providence-pd-1.avif",
    name: "Goat Lady Dairy Providence",
    ingredients: [
      "Dense",
      "Baked Bread",
      "Tang",
      "Goat Milk",
      "Raw",
      "Age: 5-12 Months",
    ],
    price: 50,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Quicke's-Mature-Cheddar-pd-1.avif",
    name: "Quicke's Mature Cheddar",
    ingredients: [
      "Crumbly",
      "Savory",
      "Acidic",
      "Cow Milk",
      "Pasteurized",
      "Age: 12 Months",
    ],
    price: 35,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Marieke-Truffle-Gouda-pd-1.avif",
    name: "Marieke Truffle Gouda",
    ingredients: [
      "Earthy",
      "Nutty",
      "Sweet",
      "Cow Milk",
      "Raw",
      "Age: 2-4 Months",
    ],
    price: 29,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Murray's-Irish-Cheddar.avif",
    name: "Murray's Irish Cheddar",
    ingredients: [
      "Tangy",
      "Buttery",
      "Smooth",
      "Sweet",
      "Cow Milk",
      "Pasteurized",
      "Age: 9 Months",
    ],
    price: 15,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Grubb-Family-Cashel-Blue.avif",
    name: "Grubb Family Cashel Blue",
    ingredients: [
      "Tangy",
      "Minerally",
      "Salty",
      "Cow Milk",
      "Sweet",
      "Cow Milk",
      "Pasteurized",
      "Age: 2-4 months",
    ],
    price: 15,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Cotswold.avif",
    name: "Cotswold",
    ingredients: [
      "Oniony",
      "Tangy",
      "Bright",
      "Cow Milk",
      "Cow Milk",
      "Pasteurized",
      "Age: 2-4 months",
    ],
    price: 15,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
];

const clubs = [
  {
    src: "/Globetrotter's-Cheese-Club.avif",
    name: "Globetrotter's Cheese Club",
    desc: "Classics From Around the World",
    price: 65,
    unit: "Month",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Cheers-to-Cheese-Club.avif",
    name: "Cheers to Cheese Club",
    desc: "A Guided Tasting to Pair With Drinks",
    price: 85,
    unit: "Month",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Cheese-Board-Club.avif",
    name: "Cheese Board Club",
    desc: "Everything You Need for a Perfect Spread",
    price: 108,
    unit: "Month",
    to: "pd/Couronne-de-Reines",
  },
];

const accompaniments = [
  {
    src: "/Wildwood-Chocolate-Salted-Caramel.avif",
    name: "Wildwood Chocolate Salted Caramel",
    ingredients: ["Chewy", "Sweet", "Balanced"],
    price: 15,
    unit: "100 g Bar",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Cloudforest-Bee-Pollen-Chocolate.avif",
    name: "Cloudforest Bee Pollen Chocolate",
    ingredients: ["Smooth", "Complex", "Toasted Milk"],
    price: 11,
    unit: "1.2 oz Bar",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Zotter-Chocolates-Tiramisu.avif",
    name: "Zotter Chocolates Tiramisu",
    ingredients: ["Chocolate", "Rum", "Coffee"],
    price: 11,
    unit: "2.47 oz Bar",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Epoisses.avif",
    name: "Epoisses",
    ingredients: [
      "Salty",
      "RumEarthy",
      "Creamy",
      "Cow Milk",
      "Pasteurized",
      "Age: 5 Weeks",
    ],
    price: 23,
    unit: "8 oz Wheel",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Meredith-Dairy-Marinated-Feta.avif",
    name: "Meredith Dairy Marinated Feta",
    ingredients: [
      "Creamy",
      "RumSpreadable",
      "Herbatious",
      "Goat",
      "Sheep Milk",
      "Pasteurized",
      "Age: Fresh",
    ],
    price: 15,
    unit: "11 oz Jar",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Murray's-Burrata.avif",
    name: "Murray's Burrata",
    ingredients: [
      "Decadent",
      "RumMilky",
      "Fresh",
      "Cow Milk",
      "Pasteurized",
      "Age: 1-2 Days",
    ],
    price: 12,
    unit: "2x4 oz Cup",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Murray's-Buffalo-Mozzarella-8oz.avif",
    name: "Murray's Buffalo Mozzarella 8oz",
    ingredients: [
      "Sweet",
      "Creamy",
      "Springy",
      "Buffalo Milk",
      "Pasteurized",
      "Age: 1-2 Days",
    ],
    price: 13,
    unit: "8 oz Cup",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Calabro-Fresh-Ricotta.avif",
    name: "Calabro Fresh Ricotta",
    ingredients: [
      "Sweet",
      "Creamy",
      "Bright",
      "Cow Milk",
      "Pasteurized",
      "Age: Fresh",
    ],
    price: 14,
    unit: "1.5 lbs Can",
    to: "pd/Couronne-de-Reines",
  },
  {
    src: "/Murray's-Lightly-Salted-Mozzarella.avif",
    name: "Murray's Lightly Salted Mozzarella",
    ingredients: [
      "Tender",
      "Lactic",
      "Sweet Cream",
      "Cow Milk",
      "Pasteurized",
      "Age: 1-2 Days",
    ],
    price: 12,
    unit: "Lb",
    to: "pd/Couronne-de-Reines",
  },
];

const recommendations = [
  {
    src: "/Jambon-De-Bayonne.avif",
    name: "Jambon De Bayonne",
    ingredients: ["Umami", "Delicate", "Light"],
    price: 18,
    unit: "3.52 OZ Pack",
  },
  {
    src: "/Raincoast-Crisps-Cranberry-Hazelnut-Crisps.avif",
    name: "Raincoast Crisps Cranberry Hazelnut Crisps",
    ingredients: ["Nutty", "Toasty", "Crunchy"],
    price: 10,
    unit: "6 oz Box",
  },
  {
    src: "/Pralus-Chocolatier-Tablette-Melissa.avif",
    name: "Pralus Chocolatier Tablette Melissa",
    ingredients: ["Milky", "Sweet", "Buttery", "Pasteurized"],
    price: 16,
    unit: "100 g Bar",
  },
];

export { cheeses, clubs, accompaniments, recommendations };
